id: I0450F452
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T12:10:32+00:00'
last_modified: '2022-06-08T11:12:01.275739+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13839
  title: ཞེ་ཆེན་གཞི་རིམ་སློབ་གྲྭའི་ཆོས་སྤྱོད་ཀྱི་རིམ་པ་ཐར་ལམ་རབ་གསལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '5849':
      image_group_id: I1KG16127
      title: ''
      total_pages: 632
      order: 1
      base_file: 5849.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
